version: '3.8'

services:
  app:
    build: .
    container_name: investtracker_app
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=invest_tracker
      - DB_USER=invest_user
      - DB_PASSWORD=secure_password_2024
      - APP_ENV=production
      - TIMEZONE=UTC
    volumes:
      - ./website:/var/www/html
      - ./storage:/var/www/html/storage
      - ./logs:/var/www/html/logs
    depends_on:
      - db
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: investtracker_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./website:/var/www/html
      - ./nginx-site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_network

  db:
    image: postgres:15-alpine
    container_name: investtracker_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: invest_tracker
      POSTGRES_USER: invest_user
      POSTGRES_PASSWORD: secure_password_2024
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge